Gateway.Web/Controllers/ExecutableScheduleController.cs
using System;
using System.Web.Mvc;
using Bagl.Cib.MIT.Logging;
using Gateway.Web.Models.Schedule.Input;
using Gateway.Web.Services.Batches.Interfaces;
using Gateway.Web.Services.Schedule.Interfaces;
using Gateway.Web.Services.Schedule.Utils;

namespace Gateway.Web.Controllers
{
    [RoutePrefix("Schedule/Executable")]
    public class ExecutableScheduleController : BaseController
    {
        private readonly IBatchConfigDataService _batchConfigDataService;
        private readonly IScheduleDataService _scheduleDataService;
        private readonly IScheduleService<ScheduleExecutableModel> _scheduleService;
        private readonly IScheduleGroupService _scheduleGroupService;

        public ExecutableScheduleController(IScheduleDataService scheduleDataService,
            IBatchConfigDataService batchConfigDataService,
            IScheduleService<ScheduleExecutableModel> scheduleService,
            IScheduleGroupService scheduleGroupService,
            ILoggingService loggingService)
           :base(loggingService)
        {
            _scheduleDataService = scheduleDataService;
            _batchConfigDataService = batchConfigDataService;
            _scheduleService = scheduleService;
            _scheduleGroupService = scheduleGroupService;
        }

        [HttpGet]
        [Route("Create")]
        public ActionResult CreateForConfiguration()
        {
            var model = new ScheduleExecutableModel();
            model.SetData(_batchConfigDataService);
            return View("Create", model);
        }

        [HttpGet]
        [Route("Create/{id}")]
        public ActionResult CreateForConfiguration(long id)
        {
            var model = new ScheduleExecutableModel();
            model.SetData(_batchConfigDataService);
            return View("Create", model);
        }

        [HttpGet]
        [Route("Create/Group/{id}")]
        public ActionResult CreateForGroup(long id)
        {
            var model = new ScheduleExecutableModel { Group = id.ToString()};
            model.SetData(_batchConfigDataService);
            return View("Create", model);
        }

        [HttpGet]
        [Route("Create/Bulk")]
        public ActionResult CreateForManyConfiguration(string items)
        {
            var model = new ScheduleExecutableModel();
            model.SetData(_batchConfigDataService);
            return View("Create", model);
        }


        [HttpGet]
        [Route("Update/{id}")]
        public ActionResult Update(long id)
        {
            var schedule = _scheduleDataService.GetSchedule(id);
            var model = schedule.ToExecutableInputModel();
            model.SetData(_batchConfigDataService);
            return View("Create", model);
        }

        [HttpPost]
        public ActionResult CreateOrUpdate(ScheduleExecutableModel model)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(model.Group) && string.IsNullOrWhiteSpace(model.GroupName) && string.IsNullOrWhiteSpace(model.Parent))
                    ModelState.AddModelError("Group", "Please ensure either a Group has been selected or a cron schedule for a new group or a parent has been specified");

                if (ModelState.IsValid)
                {
                    if (string.IsNullOrWhiteSpace(model.Parent) && string.IsNullOrWhiteSpace(model.Group))
                    {
                        var id = _scheduleGroupService.CreateOrUpdate(model.GroupName);
                        model.Group = id.ToString();
                    }

                    _scheduleService.ScheduleBatches(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            return RedirectToAction("Update","Schedule");
        }

        [HttpGet]
        [Route("{id}/Enable")]
        public ActionResult EnableSchedule(long id)
        {
            var schedule = _scheduleDataService.GetSchedule(id);
            _scheduleService.RescheduleBatches(id, null, schedule.Key);
            return RedirectToAction("Update", "Schedule");
        }
    }
}

Gateway.Web/Views/ExecutableSchedule/Create.cshtml
@model Gateway.Web.Models.Schedule.Input.ScheduleExecutableModel
@{
    Layout = "~/Views/Shared/_Layout.NoFooter.cshtml";
    ViewBag.Title = "Configuration";
    ViewBag.Current = "Schedule";
}
@{ Html.RenderPartial("_BatchConfigNav"); }

<div id="page-content-wrapper">
    <div class="hero-unit">

        <div class="container-fluid m-t-15">
            <div class="row">
                <div class="col-sm-12">

                    @if (Model.IsUpdating)
                    {
                        <h3 class="text-lowercase">Update Executable</h3>
                    }
                    else
                    {
                        <h3 class="text-lowercase">Create Executable</h3>
                    }
                    
                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="alert alert-danger" role="alert">
                            <b>The following errors have occurred:</b>
                            @Html.ValidationSummary(false, "", new {@class = "text-danger"})
                        </div>
                    }

                    <div class="m-t-20">
                        @using (@Html.BeginForm("CreateOrUpdate", "ExecutableSchedule", FormMethod.Post, new {id = "Form-" + @Model.Group}))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(m => m.ScheduleId)
                            @Html.HiddenFor(m => m.BulkUpdate)
                            @Html.HiddenFor(m => m.ExecutableConfigurationId)

                            <div class="row">
                                <div class="col-sm-2">
                                    <ul class="nav nav-pills nav-stacked">
                                        <li class="active">
                                            <a href="#batch-config" data-toggle="tab">Configuration</a>
                                        </li>
                                        <li>
                                            <a href="#group" data-toggle="tab">Group</a>
                                        </li>
                                        <li>
                                            <a href="#linked-items" data-toggle="tab">Linked Items</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-sm-10">
                                    <div class="tab-content">
                                        <div class="tab-pane fade active in" id="batch-config">
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                                                @Html.TextBoxFor(m => m.Name, new { @name = "Name", @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.PathToExe, new { @class = "control-label" })
                                                @Html.TextBoxFor(m => m.PathToExe, new { @name = "PathToExe", @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.Arguments, new { @class = "control-label" })
                                                @Html.TextAreaFor(m => m.Arguments, new { @name = "Arguments", @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="group">
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.Group, new {@class = "control-label"})
                                                <small>A group is a collection of batches that will run at the same time of the day.</small>
                                                @Html.DropDownListFor(m => m.Group, Model.Groups, new {@name = "Group", @class = "form-control"})
                                                <div class="input-group m-t-5">
                                                    @Html.TextBoxFor(m => m.GroupName, new {@name = "GroupName", placeholder = "Input a cron expression for the group OR use the 'Generate Cron' button to generate one.", @class = "form-control", @style = "margin-top: 0 !important"})
                                                    <span class="input-group-btn">
                                                        <a href="https://crontab.guru/" target="_blank" class="btn btn-default" type="button">Generate Cron</a>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="linked-items">
                                            @if (!Model.BulkUpdate)
                                            {
                                                <div class="form-group">
                                                    @Html.LabelFor(m => m.Parent, new {@class = "control-label"})
                                                    @Html.DropDownListFor(m => m.Parent, Model.Parents, new {@name = "ConfigurationId", @class = "form-control"})
                                                </div>

                                                <div class="form-group">
                                                    @Html.LabelFor(m => m.Children, new {@class = "control-label"})
                                                    @Html.ListBoxFor(m => m.Children, Model.ChildSchedules, new {@multiple = "true", @name = "ConfigurationId", @class = "form-control", style = "height: 500px;"})
                                                </div>
                                            }
                                            else
                                            {
                                                <span>Unable to modify linked items in bulk edit mode.</span>
                                            }

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row m-t-15">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-default">Save</button>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>