Gateway.Web/Models/MarketData/MarketDataResponse.cs

namespace Gateway.Web.Models.MarketData
{
    public class MarketDataResponse
    {
        public VerifiedMonikersResult VerifiedMonikersResult { get; set; }
        public bool Fallback { get; set; }
        public bool Successfull { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Gateway.Web/Models/MarketData/MissingMonikerModel.cs
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using Gateway.Web.Models.Controller;

namespace Gateway.Web.Models.MarketData
{
    public class MissingMonikerModel : BaseControllerModel
    {
        public MissingMonikerModel(string name) : base(name)
        {
        }

        public List<MonikerCheckResult> MissingMonikers { get; set; }

        public string RunDate { get; set; }
    }
}

Gateway.Web/Models/MarketData/MonikerCheckResult.cs
using System.Xml.Serialization;

namespace Gateway.Web.Models.MarketData
{
    public class MonikerCheckResult
    {
        [XmlAttribute]
        public bool Success { get; set; }
        [XmlAttribute]
        public string Moniker { get; set; }
    }

}

Gateway.Web/Models/MarketData/MonikerResult.cs
using System.Xml.Serialization;

namespace Gateway.Web.Models.MarketData
{
    public class MonikerResult
    {
        [XmlAttribute]
        public bool Success { get; set; }
        [XmlAttribute]
        public string Moniker { get; set; }
    }

}

Gateway.Web/Models/MarketData/VerifiedMonikerResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Gateway.Web.Models.MarketData
{
    public class VerifiedMonikersResult
    {
        public List<MonikerCheckResult> Failures { get; set; }
        public List<MonikerCheckResult> Successes { get; set; }
    }
}

Gateway.Web/Controllers/MarketDataController.cs

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Bagl.Cib.MIT.Logging;
using Gateway.Web.Models.MarketData;
using Gateway.Web.Services;

namespace Gateway.Web.Controllers
{
    public class MarketDataController : BaseController
    {
        private readonly IGatewayService _gateway;

        public MarketDataController(IGatewayService gateway, ILoggingService loggingService)
            : base(loggingService)
        {
            _gateway = gateway;

        }

        public async Task<ActionResult> MissingMonikersAction(DateTime? rundate)
        {
            if (rundate == DateTime.MinValue || rundate == null)
                rundate = DateTime.Now.Date;

            List<MonikerCheckResult> result = await _gateway.GetMonikers("marketdata", "verifydefaultlist/" + rundate.Value.ToString("yyyy-MM-dd"));

            var model = new MissingMonikerModel("MissingMonikers")
            {
                MissingMonikers = result,
                RunDate = rundate.Value.Date.ToString("yyyy-MM-dd")
            };

            return View("MissingMonikers", model);
        }
    }
}

Gateway.Web/Views/MarketData/MissingMonikers.cshtml
@model Gateway.Web.Models.MarketData.MissingMonikerModel
@{
    Layout = "~/Views/Shared/_Layout.NoFooter.cshtml";
    ViewBag.Title = "Market Data";
    ViewBag.Current = "Missing Monikers";
}
@{ Html.RenderPartial("~/Views/Security/_SecurityReportsNav.cshtml"); }

@using (Html.BeginForm("MissingMonikersAction", "MarketData", FormMethod.Get))
{
    <div style="margin-left: 250px; margin-top:15px">
        <input style="width: 200px;" type="date" name="rundate" value="@Model.RunDate" />
        <button class="btn btn-default" style="margin-top:-5px" type="submit" name="Go">Go</button>
    </div>
}

<div id="page-content-wrapper">
    <div class="hero-unit">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h3 class="text-lowercase">Missing Monikers</h3>
            </div>
        </div>
        <div id="report-content" style="margin-top: 10px;">
            <table style="width: 100%; white-space: nowrap" class="datatable table">
                @if (@Model.MissingMonikers.Where(x => !x.Success).Any())
                {
                    foreach (var monikeritem in @Model.MissingMonikers.Where(x => !x.Success))
                    {
                        <tr>
                            <td>@monikeritem.Moniker</td>
                            <!--<td>@monikeritem.Success</td>-->
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>None</td>
                    </tr>
                }
            </table>
        </div>
        <br />
        <h3 class="text-lowercase">Available Monikers</h3>
        <div id="report-content" style="margin-top: 10px;">
            <table style="width: 100%; white-space: nowrap" class="datatable table">
                @if (@Model.MissingMonikers.Where(x => x.Success).Any())
                {
                    foreach (var monikeritem in @Model.MissingMonikers.Where(x => x.Success))
                    {
                        <tr>
                            <td>@monikeritem.Moniker</td>
                            <!--<td>@monikeritem.Success</td>-->
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>None</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>